// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"time"
)

type Product struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	PriceInCenters int32     `json:"price_in_centers"`
	Quantity       int32     `json:"quantity"`
	CreatedAt      time.Time `json:"created_at"`
}
